spring:
  main:
    web-application-type: reactive
  application:
    name: backendbaseplatform
  cloud:
    consul:
      host: 192.168.46.199
      port: 8500
      discovery:
        instanceId: ${spring.application.name}
        health-check-url: http://${server.address}:${server.port}/actuator/health
        ip-address: ${server.address}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        health-check-interval: 10s
        health-check-timeout: 5s
        health-check-critical-timeout: 60s
        tags: backendbaseplatform
        register: true
        deregister: true
        enabled: true
        fail-fast: true
        catalog-services-watch:
          enabled: true
          delay: 10s
      config:
        import-check:
          enabled: false
  rabbitmq:
    host: 192.168.46.199
    port: 5672
    username: user
    password: bitnami
    websocket:
      destination-prefix: /app
      broker-prefix: topic
management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080
  address: 192.168.46.87