server:
  port: 8230
spring:
  application:
    name: gateway
  data:
    redis:
      host: 124.221.117.35
      port: 6379
      password: wuanfuck321.
      timeout: 50000
      database: 1

#feign接口配置60秒异常
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
gateway:
  dynamicRoute:
    enabled: true