server:
  port: 8085
spring:
  application:
    name: bus
  cloud:
    bus:
      id: ${spring.application.name}:${server.port}
      enabled: true
      trace:
        enabled: true
      destination: backendbaseplatform
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        tags: bus
        register: true
        deregister: true
        enabled: true
        fail-fast: true
management:
  endpoints:
    web:
      exposure:
        include: "*"