spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: password
      connect-timeout: 10000
      database: 0
  #  main:
#    web-application-type: reactive
  application:
    name: backendbaseplatform
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    password: wuanfuck321.
    driver-class-name: org.postgresql.Driver
    username: wuan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
#        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    loadbalancer:
      health-check:
        initial-delay: 1s
      enabled: true
      cache:
        enabled: true
      configurations: zone-preference
    bus:
      id: ${spring.application.name}:${server.port}
      enabled: true
      trace:
        enabled: true
      destination: ${spring.application.name}
    compatibility-verifier:
      enabled: false
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.uuid}}
        prefer-ip-address: true
        service-name: ${spring.application.name}
        tags: backendbaseplatform
        register: true
        deregister: true
        enabled: true
        fail-fast: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    elasticsearch:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

server:
  port: 8080

resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 50

resilience4j.timelimiter:
    configs:
        default:
            timeoutDuration: 5s
            cancelRunningFuture: true


logging:
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
#    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    web: debug

application:
  security:
    jwt:
      secret-key: 4A404E635266556A586E5A7234753778214125442A472D4B6150645367566B59
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days